#!/usr/bin/env bash
set -e
PGHOST=localhost
PGPORT=5432
PGSUPERUSER=postgres
PGSUPERPASS=postgres
NEW_DB=db_project
NEW_OWNER=sa_user
NEW_OWNER_PASS=sa_password
export PGPASSWORD=$PGSUPERPASS
psql -h $PGHOST -p $PGPORT -U $PGSUPERUSER -c "CREATE ROLE $NEW_OWNER WITH LOGIN PASSWORD '$NEW_OWNER_PASS';"
psql -h $PGHOST -p $PGPORT -U $PGSUPERUSER -c "CREATE DATABASE $NEW_DB OWNER $NEW_OWNER;"
